<div class="container">
    <h2 class="text-center">Clientes</h2>
	<div class="nav justify-content-between">
        <a class="btn btn-primary" href="<?=URL . 'clientes/add'; ?>">Adicionar</a>
        <form class="form-inline" autocomplete="off">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="<?php echo $_GET["search"] ?? '';?>" autofocus>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    <div>
        <br>        
        <b>Lista de clientes</b><div class="text-right"><b>Soma de clientes: <?php echo $soma; ?></b></div>
        <table class="table table-hover table-stripped">
            <thead>
            <tr class="bg-gray">
                <td><b>ID</b></td>
                <td><b>Nome</b></td>
                <td><b>E-mail</b></td>
                <td colspan="2" align="center">AÇÕES</td>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($todos as $cliente) { ?>
                <tr>
                    <td><?php if (isset($cliente->id)) echo htmlspecialchars($cliente->id, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($cliente->nome)) echo htmlspecialchars($cliente->nome, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($cliente->email)) echo htmlspecialchars($cliente->email, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td class='text-right'><a class='btn btn-secondary' href="<?php echo URL . 'clientes/edit/' . htmlspecialchars($cliente->id, ENT_QUOTES, 'UTF-8'); ?>">edit</a></td>
                    <td><a class='btn btn-danger' href="<?php echo URL . 'clientes/delete/' . htmlspecialchars($cliente->id, ENT_QUOTES, 'UTF-8'); ?>">delete</a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
