<div class="container">
    <h2 class="text-center">Clientes</h2>
	<div class="row justify-content-between">
        <div class="input-group col-4">
            <a class="btn btn-primary" href="<?=URL . 'clientes/add'; ?>">Adicionar</a>
        </div>
        <div class="input-group col-8 justify-content-end">
            <form class="form-inline flex-nowrap" autocomplete="off">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="<?php echo $_GET["search"] ?? '';?>" autofocus>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
    <div class="row"> 
        <div class="col-6 pr-0">     
            <b>Lista de clientes</b>
        </div>
        <div class="d-flex col-6 pl-0 justify-content-end">
            <b>Total clientes: <?php echo $soma; ?></b>
        </div>
    </div>
</div>
<div class="container">
    <div class="table-responsive">
        <table class="table table-hover table-stripped">
            <thead>
                <tr class="bg-gray">
                    <td><b>ID</b></td>
                    <td><b>Nome</b></td>
                    <td><b>E-mail</b></td>
                    <td colspan="2" align="center">AÇÕES</td>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($todos as $cliente) { ?>
                <tr>
                    <td><?php if (isset($cliente->id)) echo htmlspecialchars($cliente->id, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($cliente->nome)) echo htmlspecialchars($cliente->nome, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($cliente->email)) echo htmlspecialchars($cliente->email, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td class='text-right'><a class='btn btn-secondary' href="<?php echo URL . 'clientes/edit/' . htmlspecialchars($cliente->id, ENT_QUOTES, 'UTF-8'); ?>">edit</a></td>
                    <td><a class='btn btn-danger' href="<?php echo URL . 'clientes/delete/' . htmlspecialchars($cliente->id, ENT_QUOTES, 'UTF-8'); ?>">delete</a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
