		<!-- MENU -->
		<nav class="navbar-expand bg-dark navbar-dark">
			<ul class="navbar-nav justify-content-center">
			  <li class="nav-item"><a class="nav-link" href="<?php echo URL; ?>clientes">Cliente</a></li>
			  <li class="nav-item"><a class="nav-link" href="<?php echo URL; ?>acesso">Acesso</a></li>
			  <li class="nav-item"><a class="nav-link" href="<?php echo URL; ?>anydesk">Anydesk</a></li>
			</ul>
		</nav>
	</div>
