<div class="container">
    <h2 class="text-center">Acesso</h2>
    <div>
		<br><br>
        <form action="<?php echo URL; ?>acesso/update" method="POST" id="form" autocomplete="off">   
        <table class="table table-hover table-stripped">
            <tr><td><label>Acesso</label></td>
            <td><input class="form-control" type="text" name="acesso" value="<?php echo htmlspecialchars($um->acesso, ENT_QUOTES, 'UTF-8'); ?>" required autofocus/></td></tr>
            <td><label>tipo</label></td>
            <td>
            <select class="form-control" type="text" name="tipo_acesso" form="form" required>
                <option <?php echo ($um->tipo_acesso == "Anydesk")? "selected":"";?> value="Anydesk">Anydesk</option>
                <option <?php echo ($um->tipo_acesso == "TeamViewer")? "selected":"";?> value="TeamViewer">TeamViewer</option>
                <option <?php echo ($um->tipo_acesso == "Outros")? "selected":"";?> value="Outros">Outros</option>    
            </td></tr>
            <tr><td><label>Apelido</label></td>
            <td><input class="form-control" type="text" name="apelido" value="<?php echo htmlspecialchars($um->apelido, ENT_QUOTES, 'UTF-8'); ?>" required autofocus/></td></tr>
            <tr><td><label>Cliente</label></td>
                <td>
                    <select class="form-control" type="search"  name="id_cliente" form="form" required>
                        <?php foreach ($obj as $value) { ?>
                        <option <?php echo ($value->id == $um->id_cliente)? "selected":"";?> value="<?php echo $value->id; ?>"><?php echo $value->nome; ?></option>
                        <?php } ?>
                    </select>
                </td>
            <input type="hidden" name="field_id" value="<?php echo htmlspecialchars($um->id, ENT_QUOTES, 'UTF-8'); ?>" />
            <tr><td></td><td><input type="submit" name="submit_update_acesso" value="Update Acesso" class="btn btn-primary btn-sm"/></td></tr>
		</table>
        </form> 
    </div>
</div>
<br><br><br>
