<div class="container">
    <h2 class="text-center">Acessos</h2>
    <div class="row justify-content-between">
        <div class="input-group col-4">
            <a class="btn btn-primary" href="<?=URL . 'acesso/add'; ?>">Adicionar</a>
        </div>
        <div class="input-group col-8 justify-content-end">
            <form class="form-inline flex-nowrap" autocomplete="off">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="<?php echo $_GET["search"] ?? '';?>" autofocus>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
    <div class="row"> 
        <div class="col-6 pr-0">
            <b>Lista de Acessos </b>
        </div>
        <div class="d-flex col-6 pl-0 justify-content-end">
            <b>Total Acesso: <?php echo $soma; ?></b>
        </div>
    </div>
</div>
<div class="container">
    <div class="table-responsive">
        <table class="table table-hover table-stripped">
            <thead>
                <tr class="bg-gray">
                    <td><b>ID</b></td>
                    <td><b>ACESSO</b></td>
                    <td><b>TIPO</b></td>
                    <td><b>CLIENTE</b></td>
                    <td><b>APELIDO</b></td>
                    <td colspan="2" align="center"><b>AÇÕES</b></td>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($todos as $acesso) { ?>
                <tr>
                    <td><?php if (isset($acesso->id)) echo htmlspecialchars($acesso->id, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td onclick="copiarTexto(this.textContent)"><?php if (isset($acesso->acesso)) echo htmlspecialchars($acesso->acesso, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($acesso->tipo_acesso)) echo htmlspecialchars($acesso->tipo_acesso, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($acesso->id_cliente)) echo htmlspecialchars($obj2->umReg($acesso->id_cliente)->nome, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php if (isset($acesso->apelido)) echo htmlspecialchars($acesso->apelido, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td class='text-right'><a class='btn btn-secondary' href="<?php echo URL . 'acesso/edit/' . htmlspecialchars($acesso->id, ENT_QUOTES, 'UTF-8'); ?>">Editar</a></td>
                    <td><a class='btn btn-danger' href="<?php echo URL . 'acesso/delete/' . htmlspecialchars($acesso->id, ENT_QUOTES, 'UTF-8'); ?>">Apagar</a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<script>
  function copiarTexto(obj) {
    var dummy = document.createElement("textarea");
    document.body.appendChild(dummy);
    dummy.value = obj;
    dummy.select();
    document.execCommand("copy");
    document.body.removeChild(dummy);
    alert("Acesso Copiado: " + obj);
  }
</script>